### ISSUE TITLE
Are we using a bunch of anonymous classes in Puppet?

### ISSUE THREAD

**Issue by shawnferry** [ffrank/presentations#1]
String = Class.new slide 

Or should we expect to be seeing them in normal types and providers?

**Comment by ffrank** [comment]
The talk says that

```
Puppet::Type.newtype(:thing) { ... }
```

gives you a new class `Puppet::Type::Thing`.

This is expected and in the case of massive type proliferation spawns an equal amount of classes. Their names are quite predictable though, and this works as designed. But yes, the agent _will_ work with lots of "hidden" classes that implement the code from the Type DSL.
