### ISSUE TITLE
Does Providers.instances return all the possible providers for the target system or does it filter first

### ISSUE THREAD

**Issue by shawnferry** [ffrank/presentations#2]
or maybe this is really a RAL question

**Comment by ffrank** [comment]
The scope is just right. Enumeration of resources happens mainly at the provider level.

The provider typically returns an unfiltered list of instances for all the system entities that it can find. If this happens during prefetching, this list is then pruned by the `prefetch` hook.

The `instances` hook can also be used in other contexts, such as _purging_ through the `resources` type or other means.
